name: 'Download a Build Artifact'
description: 'Download a build artifact that was previously uploaded in the workflow by the upload-artifact action'
author: 'GitHub'
inputs: 
  name:
    description: 'Artifact name'
    required: false
  path:
    description: 'Destination path'
    required: false
  host:
    description: 'FTP server host'
    required: true
  port:
    description: 'FTP server port'
    required: false
    default: '21'
  username:
    description: 'Username for FTP access. Defaults to anonymous if not provided'
    required: false
    default: anonymous
  password:
    description: 'Password for FTP access. Defaults to anonymous if not provided'
    required: false
    default: anonymous
  secure:
    description: 'Use ftps protocol.'
    required: false
    default: 'true'
  remote-path:
    description: >
      Remote root directory to store artifacts. Defaults to root directory if not provided.
      If the path does not exist, it will be created.

      If possible, change the server-side user home directory instead of using this option.
    required: false
    default: /
outputs:
  download-path:
    description: 'Path of artifact download'
runs:
  using: 'node16'
  main: 'dist/index.js'
