name: 'Download a Build Artifact'
description: 'Download a build artifact that was previously uploaded in the workflow by the upload-artifact action'
author: 'GitHub'
inputs: 
  name:
    description: 'Artifact name'
    required: false
  path:
    description: 'Destination path'
    required: false
  host:
    required: true
  port:
    required: false
    default: 21
  username:
    required: true
  password:
    required: true
  secure:
    required: false
    default: false
  remote-path:
    required: false
    default: /
outputs:
  download-path:
    description: 'Path of artifact download'
runs:
  using: 'node16'
  main: 'dist/index.js'
